region                                               = "ap-south-1"
vpc_name                                             = "transbnk-dev-vpc"
cidr_block                                           = "10.52.0.0/16"
igw_name                                             = "transbnk-dev-igw"
pub_rt_name                                          = "transbnk-dev-pub"
nat_name                                             = "transbnk-dev-nat"
pvt_rt_name                                          = "transbnk-dev-pvt"
enable_igw_publicRouteTable_PublicSubnets_resource   = true
enable_nat_privateRouteTable_PrivateSubnets_resource = true
enable_public_web_security_group_resource            = false
enable_pub_alb_resource                              = false
enable_aws_route53_zone_resource                     = false
pub_subnet_name                                      = "transbnk-dev-pub-subnet"
DB_Middleware_pvt_subnet_name                        = "transbnk-dev-db-middleware-subnet"
DB_Middleware_private_subnets_cidr                   = ["10.52.14.0/23", "10.52.16.0/23", "10.52.18.0/23"]
public_subnets_cidr                                  = ["10.52.1.0/24", "10.52.2.0/24", "10.52.3.0/24"]
App_pvt_subnet_name                                  = "transbnk-dev-app-subnet"
App_private_subnets_cidr                             = ["10.52.24.0/21", "10.52.32.0/21", "10.52.40.0/21"]
avaialability_zones                                  = ["ap-south-1a", "ap-south-1b", "ap-south-1c"]